# AI工学101 — 第1回

## AIは「数字の世界」で動いている 〜 NumPy入門 〜

**所要時間：60〜90分**

* 📖 講義：約20分
* 💻 実習：約40分
* ✍️ 演習：約20分

---

# このブートキャンプについて

ようこそ、AI工学101へ！

この100日では、

> **「AIライブラリを使える人」ではなく、「AIが何を計算しているか理解して実装できる人」**

を目指します。

カリキュラムの流れは次のとおりです。

```
Python基礎
    ↓
NumPy
    ↓
データ前処理
    ↓
scikit-learn
    ↓
機械学習
    ↓
PyTorch
    ↓
ニューラルネットワーク
    ↓
ミニプロジェクト
```

Python経験がある前提で進めますが、「AIのためのPython」を一つずつ積み上げていきます。

---

# 今日のゴール

今日のテーマは

> **NumPyの配列（ndarray）に慣れること**

です。

ニューラルネットワークも画像認識もLLMも、最終的には**大量の数値配列**を計算しています。

NumPyは、その配列を高速に扱うためのライブラリです。

---

# 講義（20分）

## AIは何を見ているの？

例えば猫の画像。

人間には「猫」に見えますが、コンピュータには

```
154 121  87 ...
210 198 165 ...
...
```

という数値の集まりです。

画像だけでなく、

* 音声
* テキスト
* センサーデータ

も最終的には数値として扱われます。

つまりAI開発では、

> **「数値データをどう加工し、どう計算するか」**

が仕事の中心になります。

---

## Pythonのリストとの違い

普通のPythonでは

```python
numbers = [1, 2, 3]
```

と書けます。

NumPyでは

```python
import numpy as np

numbers = np.array([1, 2, 3])
```

となります。

見た目は似ていますが、

NumPy配列は

* 高速
* メモリ効率が良い
* 数学計算が得意

という特徴があります。

---

## ndarray

NumPyで最も重要なのが

```python
ndarray
```

です。

名前は

```
n-dimensional array
```

つまり

> **多次元配列**

という意味です。

AIではこの型ばかり扱います。

---

# 実習（40分）

## ① NumPyをインポート

```python
import numpy as np
```

---

## ② 1次元配列

```python
a = np.array([1, 2, 3])

print(a)
```

出力

```
[1 2 3]
```

---

## ③ 型を確認

```python
print(type(a))
```

期待される結果

```
<class 'numpy.ndarray'>
```

---

## ④ 2次元配列

```python
A = np.array([
    [1, 2],
    [3, 4]
])

print(A)
```

---

## ⑤ shape

```python
print(A.shape)
```

出力

```
(2, 2)
```

これは

```
2行
2列
```

を意味します。

---

## ⑥ size

```python
print(A.size)
```

結果

```
4
```

---

## ⑦ dtype

```python
print(A.dtype)
```

結果例

```
int64
```

---

## ⑧ 0で埋める

```python
zeros = np.zeros((3, 4))

print(zeros)
```

---

## ⑨ 1で埋める

```python
ones = np.ones((2, 5))

print(ones)
```

---

## ⑩ 乱数

```python
random_matrix = np.random.rand(3, 3)

print(random_matrix)
```

毎回違う値になります。

---

## ⑪ 足し算

```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A + B)
```

---

## ⑫ 要素ごとの掛け算

```python
print(A * B)
```

---

## ⑬ 行列積

```python
print(A @ B)
```

ここが最重要です。

ニューラルネットワークでは、

```
入力 × 重み
```

という計算が何度も出てきます。

この「×」が実際には**行列積**です。

---

# 演習（20分）

### 演習1

次の配列を作ってみましょう。

```
1 2 3
4 5 6
```

---

### 演習2

作成した配列について

* shape
* size
* dtype

を表示してください。

---

### 演習3

以下を作成してください。

* 5×5の0行列
* 4×4の1行列

---

### 演習4

3×3の乱数行列を作成してください。

---

### 演習5

次の2つの行列について、

```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
```

以下を実行し、それぞれ結果の違いを確認してください。

```python
A + B
A * B
A @ B
```

---

# 今日のポイント

今日覚えてほしいのは、この6つです。

* `np.array()`
* `shape`
* `size`
* `dtype`
* `np.zeros()`
* `@`（行列積）

この6つは、今後NumPy・scikit-learn・PyTorchを通して何度も登場します。

---

# 発展課題（余裕があれば）

次の関数を試し、それぞれの役割を調べてみましょう。

```python
np.arange()
np.linspace()
reshape()
```

特に `reshape()` は、AIでデータの形を整えるときに頻繁に使います。

---

# 次回予告

**第2回：ベクトル演算とブロードキャスト**

NumPyが「ただの配列ライブラリ」ではない理由が見えてきます。ベクトル化やブロードキャストを理解すると、AIコードがシンプルで高速になる理由を体感できるようになります。

In [ ]:
import numpy as np

a = np.array([[1, 2, 3]])
print(a)

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

print(A.shape)

[[1 2 3]]
[[1 2 3]
 [4 5 6]]


In [3]:
# 問1
# 次の配列を作ろう。
# 1 2 3
# 4 5 6

A = np.array([[1, 2, 3]])
B= np.array([[4, 5, 6]])

# 問2
# shapeを表示してみよう。

print(A.shape)

# 問3
# 3×3の0行列を作ろう。

zero = np.zeros((3, 3))
print(zero)

# 問4
# 5×5の乱数行列を作ろう。

rand = np.random.rand(5, 5)
print(rand)

# 問5
# 次を計算してみよう。
# A+B

print(A + B)

# A*B

print(A * B)

# A@B

print(A @ B.T)

# 違いを確認してみよう。

(1, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.41511167 0.5086964  0.81589085 0.72343491 0.11480482]
 [0.62733549 0.40725307 0.20312541 0.91256653 0.32901531]
 [0.24832126 0.15770175 0.12751329 0.23588112 0.27825133]
 [0.91437699 0.21517455 0.42151506 0.37860922 0.3967806 ]
 [0.45342505 0.41854867 0.64155066 0.02926148 0.89978481]]
[[5 7 9]]
[[ 4 10 18]]
[[32]]
