# AI工学101 — 第3回

## NumPyでデータを切る・選ぶ・絞る

今日は前回の**ベクトル演算・ブロードキャスト**の続き。テーマは **インデックス・スライス・Boolean Mask** です。

ここは地味に見えて、機械学習では猛烈に使います。

> 「1000件のデータから条件に合う237件だけ取り出す」

みたいな操作を、Pythonの `for` 文なしで書けるようになります。

**所要時間：60〜90分 / 講義20分 + 実習40分 + 演習20分**

---

## 📖 講義：AIにとって「データを選ぶ」とは

こんなデータがあるとします。

```python
import numpy as np

scores = np.array([42, 78, 91, 55, 83])
```

3番目の値が欲しいなら、

```python
scores[2]
```

結果は、

```text
91
```

Pythonと同じく**0始まり**ですね。

そしてNumPyでは、もっと強力なことができます。

```python
scores[scores >= 80]
```

結果：

```text
[91 83]
```

この一行では、

```text
scores >= 80
      ↓
[False, False, True, False, True]
      ↓
Trueの場所だけ取得
      ↓
[91, 83]
```

という処理が行われています。

これが **Boolean Mask（真偽値マスク）**。

後でscikit-learnを使うと、

```text
データ
 ↓
異常値を除く
 ↓
特定クラスを抽出
 ↓
訓練データとテストデータに分割
 ↓
モデルへ投入
```

といった処理を大量に行います。

つまり今日は**モデルに食わせるデータを料理する技術**です。🍳

---

# 💻 実習1：インデックス

まず一次元配列。

```python
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[2])
print(a[-1])
```

結果を予想してから実行してみてください。

特に、

```python
a[-1]
```

は「最後の要素」です。

---

# 💻 実習2：スライス

```python
print(a[1:4])
```

これは、

```text
index    0   1   2   3   4
value   10  20  30  40  50
             └───────┘
```

なので、

```text
[20 30 40]
```

になります。

基本形は、

```python
a[start:stop:step]
```

です。

例えば、

```python
a[::2]
```

なら1個飛ばし。

```text
[10 30 50]
```

---

# 💻 実習3：二次元配列を切る

ここからAIっぽくなります。

```python
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])
```

shapeを確認。

```python
print(X.shape)
```

```text
(4, 3)
```

4サンプル × 3特徴量、と考えることもできます。

---

## 行を取り出す

```python
print(X[1])
```

結果：

```text
[40 50 60]
```

---

## 一要素を取り出す

```python
print(X[1, 2])
```

結果：

```text
60
```

NumPyでは、

```python
X[行, 列]
```

と覚えると分かりやすいです。

---

## 列を丸ごと取り出す

```python
print(X[:, 1])
```

結果：

```text
[20 50 80 110]
```

この `:` が重要。

```text
X[:, 1]
│ │  └─ 1列目
│ └──── 全行
└────── X
```

つまり**全サンプルについて、特定の特徴量だけ取得**できます。

これは今後めちゃくちゃ使います。

---

# 💻 実習4：Boolean Mask

本日の主役です。

```python
scores = np.array([42, 78, 91, 55, 83])

mask = scores >= 80

print(mask)
```

結果：

```text
[False False  True False  True]
```

そして、

```python
print(scores[mask])
```

結果：

```text
[91 83]
```

一行でも書けます。

```python
scores[scores >= 80]
```

---

# 💻 実習5：複数条件

「60以上90未満」を取り出したい。

NumPyではこうします。

```python
scores[(scores >= 60) & (scores < 90)]
```

結果：

```text
[78 83]
```

ここで注意。

Pythonの、

```python
and
```

ではなく、

```python
&
```

を使います。

ORなら、

```python
|
```

です。

そして各条件を **`()` で囲む**。

これはNumPy初心者が一度は踏む地雷です💣

```python
(scores >= 60) & (scores < 90)
```

の形ごと覚えてしまってOK。

---

# 💻 実習6：実際のデータっぽくする

5人について、

```text
[勉強時間, テスト点数]
```

があるとします。

```python
data = np.array([
    [1.0, 45],
    [2.5, 62],
    [3.0, 70],
    [4.5, 88],
    [6.0, 95]
])
```

点数だけ取得。

```python
scores = data[:, 1]

print(scores)
```

```text
[45. 62. 70. 88. 95.]
```

80点以上の人を抽出します。

```python
high_score = data[data[:, 1] >= 80]

print(high_score)
```

結果：

```text
[[ 4.5 88. ]
 [ 6.  95. ]]
```

おお。

**「点数が80以上の行を丸ごと取得」**

できました。

これ、もう小さいながら**データサイエンスのコード**です。

---

# ✍️ 演習

ここからはレベル君のターン。

次のデータを使います。

```python
data = np.array([
    [25, 150],
    [30, 180],
    [35, 170],
    [40, 200],
    [45, 160],
    [50, 220]
])
```

各行を、

```text
[年齢, スコア]
```

とします。

### 問1〜5

1. すべての「年齢」だけを取得してください。
2. すべての「スコア」だけを取得してください。
3. スコアが180以上の人を、**行ごと**抽出してください。
4. 年齢が30以上45以下の人を抽出してください。
5. **年齢35以上 かつ スコア180以上**の人を抽出してください。

特に問5が今日のボス戦です👾

ヒントだけ置いておきます。

```python
data[
    (条件1) & (条件2)
]
```

答えはまだ書かないので、実際にNumPyで組んでみよう。

---

## 🌿 今日の到達点

第1回では「NumPy配列を作る」、第2回では「配列をまとめて計算する」、そして今回は、

> **配列から必要なデータだけ選択する**

ところまで来ました。

ここまでの3回で、

```python
X[:, 0]
X * 10
X[X[:, 1] >= 80]
A @ B
```

みたいな、**機械学習コードで普通に出てくるNumPy記法**がだいぶ読めるようになっています。

次の**第4回は `reshape`・次元・axis**。

ここで `(100,)` と `(100, 1)` が「似てるようで全然違う」という、AIエンジニアを定期的に殴ってくる **shape地獄🔥** に入ります。

In [ ]:
import numpy as np

a = np.array([10,20,30,40,50])

print(a[0])
print(a[2])
print(a[-1])