# AI工学101 — 第2回

## テーマ：**NumPyの真価 〜 ベクトル演算とブロードキャスト 〜**

**所要時間：60〜90分**

* 📖 講義：約20分
* 💻 実習：約40分
* ✍️ 演習：約20分

---

# 前回の復習（5分）

前回は次の6つを学びました。

* `np.array()`
* `shape`
* `size`
* `dtype`
* `np.zeros()`
* `@`（行列積）

今日はその続きです。

---

# 今日のゴール

今日は

> **for文を書かずに大量の計算をする方法**

を身につけます。

NumPyが速い理由はここにあります。

---

# 講義（20分）

## Pythonらしい書き方

例えば全員に1点加点したいとします。

普通のPythonなら

```python
scores = [50, 60, 70]

new_scores = []

for s in scores:
    new_scores.append(s + 1)
```

AIでもできますが、遅いです。

---

NumPyなら

```python
import numpy as np

scores = np.array([50, 60, 70])

print(scores + 1)
```

結果

```
[51 61 71]
```

for文がありません。

NumPyは内部で高速なC言語実装を使っているため、このような書き方が速くなります。

---

## ベクトル化（Vectorization）

この

```
配列同士をまとめて計算する
```

考え方を

**ベクトル化**

と言います。

AIコードでは毎日のように使います。

---

## ブロードキャスト

NumPyには便利な仕組みがあります。

```python
A = np.array([
    [1,2],
    [3,4]
])

print(A + 10)
```

結果

```
11 12
13 14
```

10が自動的に全要素へ広がっています。

これが

**ブロードキャスト**

です。

---

## なぜ重要？

例えば画像。

```
高さ × 幅 × RGB
```

全部の画素に

```
255で割る
```

ことがよくあります。

```python
image = image / 255
```

これだけで終わります。

for文は不要です。

---

# 実習（40分）

## ① ベクトル同士

```python
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a + b)
```

---

## ② 引き算

```python
print(a - b)
```

---

## ③ 掛け算

```python
print(a * b)
```

---

## ④ 割り算

```python
print(a / b)
```

---

## ⑤ スカラー演算

```python
print(a + 100)

print(a * 10)

print(a / 2)
```

---

## ⑥ ブロードキャスト

```python
A = np.array([
    [1,2],
    [3,4]
])

print(A + 10)
```

---

## ⑦ 行ごとに足す

```python
A = np.array([
    [1,2],
    [3,4]
])

v = np.array([10,20])

print(A + v)
```

結果

```
11 22
13 24
```

NumPyが自動で形を合わせています。

---

## ⑧ 列ごとに足す

```python
v = np.array([
    [10],
    [20]
])

print(A + v)
```

結果

```
11 12
23 24
```

同じ「足し算」でも、ベクトルの形によって結果が変わることに注目しましょう。

---

## ⑨ 平均を求める

```python
scores = np.array([70,80,90])

print(scores.mean())
```

---

## ⑩ 最大値・最小値

```python
print(scores.max())

print(scores.min())
```

データ分析や前処理では頻繁に使います。

---

# 演習（20分）

### 演習1

次の配列を作成してください。

```python
a = np.array([2,4,6,8])
```

以下を実行して結果を確認しましょう。

```python
a + 5
a * 3
a / 2
```

---

### 演習2

次の2つの配列を足してください。

```python
a = np.array([1,2,3])

b = np.array([10,20,30])
```

---

### 演習3

次の行列に

```python
[100, 200]
```

をブロードキャストして足してみましょう。

```python
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
```

---

### 演習4

次の配列について

```python
scores = np.array([65,72,81,94,58])
```

以下を求めてください。

* 平均
* 最大値
* 最小値

---

# 今日のポイント

今日はAIコードを書く上で最も重要な考え方を学びました。

* **ベクトル化**：for文ではなく、配列全体を一度に計算する。
* **ブロードキャスト**：形の異なる配列同士でも、条件が合えば自動的に計算できる。

この2つを理解すると、NumPyやPyTorchのコードが「なぜこんなに短いのか」が見えてきます。

---

# 発展課題

`axis` 引数を使って、行方向・列方向ごとに平均を求めてみましょう。

```python
A.mean(axis=0)
A.mean(axis=1)
```

結果を見比べて、「どの方向に集計しているのか」を自分の言葉で説明できれば十分です。

---

## 次回予告

**第3回：NumPyインデックス・スライス・マスク操作**

AI開発では「必要なデータだけ取り出す」操作が非常に多くあります。次回は、NumPyでデータを自在に切り出すテクニックを学びます。

In [3]:
import numpy as np

# 演習（20分）
### 演習1

# 次の配列を作成してください。

# ```python
# a = np.array([2,4,6,8])
# ```

# 以下を実行して結果を確認しましょう。

# ```python
# a + 5
# a * 3
# a / 2
# ```

a = np.array([2,4,6,8])
print(a + 5)
print(a * 3)
print(a / 2)

### 演習2

# 次の2つの配列を足してください。

# ```python
# a = np.array([1,2,3])

# b = np.array([10,20,30])
# ```

a = np.array([1,2,3])
b = np.array([10,20,30])
print(a + b)

### 演習3

# 次の行列に

# ```python
# [100, 200]
# ```

# をブロードキャストして足してみましょう。

# ```python
# A = np.array([
#     [1,2],
#     [3,4],
#     [5,6]
# ])
# ```

A = np.array([
    [1,2],  
    [3,4],
    [5,6]
])
print(A + np.array([100, 200]))

### 演習4

# 次の配列について

# ```python
# scores = np.array([65,72,81,94,58])
# ```

# 以下を求めてください。

# * 平均
# * 最大値
# * 最小値

scores = np.array([65,72,81,94,58])
print(scores.mean())
print(scores.max())
print(scores.min())

# 発展課題

# `axis` 引数を使って、行方向・列方向ごとに平均を求めてみましょう。

# ```python
# A.mean(axis=0)
# A.mean(axis=1)
# ```

print(A.mean(axis=0))
print(A.mean(axis=1))

[ 7  9 11 13]
[ 6 12 18 24]
[1. 2. 3. 4.]
[11 22 33]
[[101 202]
 [103 204]
 [105 206]]
74.0
94
58
[3. 4.]
[1.5 3.5 5.5]
