# AI工学101 — 第4回

## shape地獄へようこそ 🔥 `reshape`・次元・`axis`

よし、今回はちゃんと**第3回の続き**だぞ😂
前回までで「作る → 計算する → 選ぶ」まで来ました。

今日はAIコードで頻発する、

```text
ValueError: shapes ... not aligned
```

系エラーと仲良くなる回です。

**所要時間：60〜90分**
講義20分 ＋ 実習40〜50分 ＋ 演習20分

---

## 📖 講義：shapeは「データの意味」でもある

まずこれ。

```python
import numpy as np

a = np.array([10, 20, 30])

print(a.shape)
```

結果：

```text
(3,)
```

3個の数字だから `(3,)`。

ではこれは？

```python
b = np.array([
    [10],
    [20],
    [30]
])

print(b.shape)
```

結果：

```text
(3, 1)
```

似てる。

でも、

```text
(3,)      ← 1次元ベクトル

(3, 1)    ← 3行1列の2次元行列
```

**別物です。**

さらに、

```python
c = np.array([[10, 20, 30]])
```

なら、

```text
(1, 3)
```

です。

図にすると、

```text
(3,)

[10 20 30]


(1, 3)

[[10 20 30]]


(3, 1)

[[10]
 [20]
 [30]]
```

同じ3個の数字なのに構造が違う。

ここが重要です。

---

## AIではshapeに意味がある

例えば機械学習では、典型的に入力データ `X` を、

```text
(samples, features)
```

というshapeで持ちます。

100人について、

```text
年齢
身長
体重
```

を記録したなら、

```text
(100, 3)
```

になります。

つまり、

```python
X.shape
```

を見れば、

> 100サンプル × 3特徴量

だと分かる。

後のPyTorchではさらに、

```text
(batch, channel, height, width)
```

などが出てきます。

だからAIエンジニアは、コードを読むときかなりの頻度で、

**「今このtensor、shape何？」**

と考えています。

shapeは住所みたいなもんです。

---

# 💻 実習1：`ndim`

次元数を調べてみます。

```python
a = np.array([1, 2, 3])

b = np.array([
    [1, 2, 3]
])

c = np.array([
    [1],
    [2],
    [3]
])

print(a.ndim)
print(b.ndim)
print(c.ndim)
```

予想してから実行してみてください。

結果は、

```text
1
2
2
```

です。

つまり、

```text
shape       ndim

(3,)          1
(1, 3)        2
(3, 1)        2
```

となります。

---

# 💻 実習2：`reshape`

6個の数字を作ります。

```python
a = np.arange(1, 7)

print(a)
print(a.shape)
```

結果：

```text
[1 2 3 4 5 6]

(6,)
```

これを2×3に変形。

```python
A = a.reshape(2, 3)

print(A)
```

```text
[[1 2 3]
 [4 5 6]]
```

shape：

```python
print(A.shape)
```

```text
(2, 3)
```

---

## 3×2にもできる

```python
B = a.reshape(3, 2)

print(B)
```

```text
[[1 2]
 [3 4]
 [5 6]]
```

重要なのは、

> **要素数そのものは変わらない**

ということ。

6個の数字なら、

```text
2 × 3 = 6
3 × 2 = 6
1 × 6 = 6
6 × 1 = 6
```

はOK。

しかし、

```python
a.reshape(4, 2)
```

は無理です。

8個必要なのに6個しかありません。

NumPy「湿った肉よ、算数をしろ」

となります。

---

# 💻 実習3：`-1` に計算させる

これはめちゃくちゃ便利。

```python
a.reshape(2, -1)
```

NumPyが、

```text
6要素
↓
2行
↓
じゃあ3列ですね
```

と推論します。

結果：

```text
(2, 3)
```

逆もできます。

```python
a.reshape(-1, 2)
```

結果：

```text
(3, 2)
```

AIコードで、

```python
X.reshape(-1, 1)
```

という記述を見かけたら、

> 「行数は自動計算して、1列の二次元データにしている」

と読めます。

---

# 💻 実習4：`axis` を理解する

ここは今日一番重要です。

```python
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
```

shapeは、

```text
(2, 3)
```

です。

まず全部の平均。

```python
A.mean()
```

結果：

```text
35
```

では、

```python
A.mean(axis=0)
```

を実行。

結果：

```text
[25. 35. 45.]
```

なぜ？

```text
10   20   30
↓    ↓    ↓
40   50   60

25   35   45
```

**axis=0方向を潰して集計**しています。

---

次。

```python
A.mean(axis=1)
```

結果：

```text
[20. 50.]
```

つまり、

```text
10 → 20 → 30  = 20

40 → 50 → 60  = 50
```

です。

ここで、

> axis=0 は縦
> axis=1 は横

とだけ丸暗記すると、3次元以上で事故ります。

より正確には、

> **指定したaxisを消すように集計する**

と理解してください。

---

# 💻 実習5：shapeが消える様子を見る

```python
print(A.shape)
```

```text
(2, 3)
```

そして、

```python
x = A.mean(axis=0)

print(x.shape)
```

結果：

```text
(3,)
```

もともと、

```text
(2, 3)
 ↑
axis=0
```

だったものから0番目の軸が消え、

```text
(3,)
```

になった。

一方、

```python
y = A.mean(axis=1)

print(y.shape)
```

なら、

```text
(2,)
```

です。

この**「どの軸が消えた？」**という見方がかなり強いです。

---

# 💻 実習6：標準化を少しだけ先取り

機械学習で非常によく行う処理です。

```python
X = np.array([
    [160, 50],
    [170, 60],
    [180, 70]
])
```

仮に、

```text
身長 | 体重
```

だとします。

特徴量ごとの平均：

```python
mean = X.mean(axis=0)

print(mean)
```

結果：

```text
[170.  60.]
```

そして、

```python
X_centered = X - mean

print(X_centered)
```

すると、

```text
[[-10. -10.]
 [  0.   0.]
 [ 10.  10.]]
```

第2回の**ブロードキャスト**が帰ってきました。

つまり今、

```text
axisによる集計
      ↓
平均ベクトル
      ↓
ブロードキャスト
      ↓
データの中心化
```

と、以前の知識が接続されています。

これが後でscikit-learnの前処理につながります。

---

# ✍️ 演習：shape迷宮

次のデータを使います。

```python
X = np.arange(1, 13)
```

### 問1

現在の、

```python
X.shape
X.ndim
```

を確認してください。

### 問2

`reshape()` を使って、

```text
4行 × 3列
```

にしてください。

### 問3

その行列について、

```python
mean(axis=0)
```

を求めてください。

結果のshapeも確認します。

### 問4

今度は、

```python
mean(axis=1)
```

を求め、shapeを確認してください。

### 問5：ボス戦 👾

次があります。

```python
x = np.array([10, 20, 30, 40])
```

これを、

```text
[[10],
 [20],
 [30],
 [40]]
```

という形に変換してください。

ただし数字を手入力し直してはいけません。

`reshape()` を使います。

そして最終的な、

```python
x.shape
```

が、

```text
(4, 1)
```

になれば勝利です。

---

## 今日の到達点

ここまで4回で、

```text
第1回  ndarray・行列演算
        ↓
第2回  ベクトル化・broadcast
        ↓
第3回  slice・Boolean Mask
        ↓
第4回  reshape・shape・axis
```

まで来ました。

これ、単なるNumPy関数の暗記ではありません。

例えば、

```python
X[X[:, 1] >= 80]
```

を見て「条件抽出だ」と分かり、

```python
X.mean(axis=0)
```

を見て「サンプル方向を集約して特徴量ごとの平均を出してるな」と読める。

さらに、

```python
X.reshape(-1, 1)
```

を見て「1特徴量の二次元入力に整形してる」と読める。

**AIコードを読むための文法が少しずつ揃ってきています。**

次の**第5回は「線形代数をNumPyで実装する」**。

内積、行列積、転置、そして

[
y = Wx + b
]

に入ります。

ここでとうとう、今まで触ってきたNumPyが**ニューラルネットワークの計算そのもの**に接続します。リュール先生、いよいよAIの心臓部へ連れていきますぞ👨‍🏫🌿