# AI工学101 — 第8回

## NumPyの乱数・サンプリング・再現性 〜 機械学習実験の土台を作る 〜

前回は、**欠損値・外れ値・データクリーニング**を学びました。

今回は、機械学習で必ず出てくる

* 乱数（Random Number）
* サンプリング
* シャッフル
* 再現性（Reproducibility）

を扱います。

ここは「実験科学」としてのAIの入り口です。

**所要時間：60〜90分**

* 📖 講義：約20分
* 💻 実習：約40分
* ✍️ 演習：約20分

---

# 📖 講義：なぜ乱数が必要なの？

AIでは意外なほど乱数を使います。

例えば、

* データをシャッフルする
* 学習データとテストデータに分ける
* ニューラルネットワークの重みを初期化する
* ランダムサンプリングする

などです。

しかし困ることがあります。

今日実験した結果が

```
Accuracy = 93%
```

だったのに、

明日同じコードを動かすと

```
Accuracy = 91%
```

になる。

それでは研究も開発も困ります。

そこで重要なのが

> **再現性（Reproducibility）**

です。

---

# 💻 実習1：乱数を作る

```python
import numpy as np

x = np.random.rand(5)

print(x)
```

例えば

```
[0.23 0.81 0.17 0.52 0.94]
```

のようになります。

毎回違います。

---

## 整数乱数

```python
np.random.randint(0, 10, size=5)
```

例

```
[3 8 1 0 7]
```

これは

```
0以上10未満
```

から5個取り出しています。

---

# 💻 実習2：seed

ここが超重要。

```python
np.random.seed(42)

print(np.random.rand(5))
```

何回実行しても

同じ結果になります。

つまり

```
seed
```

とは

> **乱数のスタート地点**

です。

研究論文でも

```
random_state=42
```

などが頻繁に登場します。

---

# 💻 実習3：配列をシャッフル

```python
data = np.arange(10)

print(data)
```

```
[0 1 2 3 4 5 6 7 8 9]
```

シャッフルします。

```python
np.random.shuffle(data)

print(data)
```

順番だけ変わります。

---

## 注意

```python
shuffle()
```

は

**元データを書き換えます。**

コピーしたいなら

```python
shuffled = np.random.permutation(data)
```

を使います。

---

# 💻 実習4：サンプリング

100人から5人選びます。

```python
people = np.arange(100)

sample = np.random.choice(
    people,
    size=5,
    replace=False
)

print(sample)
```

ここで

```python
replace=False
```

なので

同じ人は2回選ばれません。

---

もし

```python
replace=True
```

なら

```
12
12
53
78
78
```

みたいなことも起こります。

---

# 📖 学習データとテストデータ

機械学習では

全部のデータで学習すると、

本当に賢くなったか分かりません。

そこで

```
1000件

↓

800件 学習

200件 評価
```

のように分けます。

これを

```
train/test split
```

と言います。

今日はNumPyだけで作ります。

---

# 💻 実習5：train/testを作る

データを作ります。

```python
X = np.arange(20)

print(X)
```

まずシャッフル。

```python
np.random.seed(42)

idx = np.random.permutation(len(X))
```

確認。

```python
print(idx)
```

---

並べ替え。

```python
X = X[idx]

print(X)
```

---

8割で分割。

```python
split = int(len(X) * 0.8)

train = X[:split]

test = X[split:]
```

確認。

```python
print(train)

print(test)
```

これで

```
train
test
```

ができました。

---

# 💻 実習6：特徴量とラベルも一緒に並べ替える

ここが実務では重要。

```python
X = np.array([
    [160,50],
    [170,60],
    [180,70],
    [190,80]
])

y = np.array([
    0,
    1,
    0,
    1
])
```

シャッフル。

```python
idx = np.random.permutation(len(X))

X = X[idx]

y = y[idx]
```

すると

対応が崩れません。

これを忘れると

```
入力

↓

正解ラベル

↓

ぐちゃぐちゃ
```

になり、

モデルが壊れます。

---

# 💻 実習7：乱数で重みを作る

第5回では

```python
W = np.array(...)
```

と手入力しました。

実際は

```python
W = np.random.randn(2,3)
```

のように作ります。

確認。

```python
print(W)
```

これが

ニューラルネットワークの

**初期重み**

になります。

PyTorchでは

この処理が自動で行われています。

---

# ✍️ 演習

今日のデータ。

```python
X = np.arange(30)
```

---

### 問1

乱数seedを

```python
42
```

に設定してください。

---

### 問2

`X` をシャッフルしてください。

---

### 問3

7:3に分割してください。

```
train

test
```

を作ります。

---

### 問4

100人の中から

10人を重複なしで抽出してください。

---

### 問5（ボス戦👾）

次があります。

```python
X = np.array([
    [1,10],
    [2,20],
    [3,30],
    [4,40],
    [5,50]
])

y = np.array([
    0,
    1,
    0,
    1,
    0
])
```

`X` と `y` の対応を崩さず、

ランダムに並べ替えてください。

---

# 🌿 今日のまとめ

今日は、機械学習実験の基本となる「乱数との付き合い方」を学びました。

重要なのは次の4点です。

* `np.random.seed()`：実験を再現できるようにする。
* `np.random.permutation()`：データを安全にシャッフルする。
* `np.random.choice()`：ランダムサンプリングを行う。
* **インデックスを使って `X` と `y` を一緒に並べ替える**：特徴量と正解ラベルの対応を保つ。

これらは、後で scikit-learn の `train_test_split()` を使うときに、「ライブラリが内部で何をしているのか」を理解する土台になります。

---

## 次回予告

**第9回：NumPyで探索的データ分析（EDA）の基礎**

いよいよ「データを眺めて理解する」工程に入ります。最小値・最大値・分位数・ヒストグラムの考え方を学び、機械学習を始める前に「まずデータを見る」というAIエンジニア・データサイエンティスト共通の習慣を身につけます。

In [3]:
import numpy as np

# 演習

# 今日のデータ。
Z = np.arange(30)
print(Z)

# 問1
# 乱数seedを42に設定してください。
np.random.seed(42)

# 問2
# `Z` をシャッフルしてください。
idx = np.random.permutation(Z)
print("idx:", idx)
Z=Z[idx]
print(Z)

# 問3
# 7:3に分割してください。
split = int(len(Z)*0.7)
train = Z[:split]
test = Z[split:]
print("split:", split)
print("train:", train)
print("test:", test)

# 問4
# 100人の中から10人を重複なしで抽出してください。
people = np.arange(100)
sample = np.random.choice(
    people,
    size=10,
    replace=False
)
print(sample)

# 問5（ボス戦👾）
# 次があります。

X = np.array([
    [1,10],
    [2,20],
    [3,30],
    [4,40],
    [5,50]
])

y = np.array([
    0,
    1,
    0,
    1,
    0
])

# `X` と `y` の対応を崩さず、
# ランダムに並べ替えてください。

idx2 = np.random.permutation(len(X))
X = X[idx2]
y = y[idx2]
print("idx:", idx2, "/X:", X, "/y:", y)

# | 関数                              | 何をする？            | 戻り値      |
# | ------------------------------- | ---------------- | -------- |
# | `np.random.shuffle(Z)`          | Z自身をシャッフル        | `None`   |
# | `np.random.permutation(Z)`      | シャッフルされた新しい配列を返す | 配列       |
# | `np.random.permutation(len(X))` | シャッフル用インデックスを作る  | インデックス配列 |


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
idx: [27 15 23 17  8  9 28 24 12  0  4 16  5 13 11 22  1  2 25  3 21 26 18 29
 20  7 10 14 19  6]
[27 15 23 17  8  9 28 24 12  0  4 16  5 13 11 22  1  2 25  3 21 26 18 29
 20  7 10 14 19  6]
split: 21
train: [27 15 23 17  8  9 28 24 12  0  4 16  5 13 11 22  1  2 25  3 21]
test: [26 18 29 20  7 10 14 19  6]
[12 64 86 56 19 98 73 44 37 27]
idx: [3 0 1 2 4] /X: [[ 4 40]
 [ 1 10]
 [ 2 20]
 [ 3 30]
 [ 5 50]] /y: [1 0 1 0 0]
