🤣🤣🤣

その通り！！！！

僕がタスクの文面に引っ張られて、**第1回をもう一回開講してしまった**。

完全に

👨‍🏫「はい、第1回です。」
👨‍🏫「……さて、第1回を始めます。」

ってやってた。すまんwwwww

---

じゃあ次からは認知科学100課題と同じ形式にしよう。

- 1回やった内容は飛ばす
- 「第2回」「第3回」…と順番に進める
- 前回の内容を少し復習
- 新しい概念を学ぶ
- 実習を中心に進める

つまり**連続講義**にする。

なので次は

> **AI工学101 第2回**
> **NumPyの真価！ ベクトル演算とブロードキャスト**

から始めるね🌿

この方が「今日の授業」がちゃんと積み重なっていく感じになって、ブートキャンプらしくなる。

# AI工学101 — 第2回
## テーマ：**NumPyの真価 〜 ベクトル演算とブロードキャスト 〜**

**所要時間：60〜90分**

- 📖 講義：約20分
- 💻 実習：約40分
- ✍️ 演習：約20分

---

# 前回の復習（5分）

前回は次の6つを学びました。

- `np.array()`
- `shape`
- `size`
- `dtype`
- `np.zeros()`
- `@`（行列積）

今日はその続きです。

---

# 今日のゴール

今日は

> **for文を書かずに大量の計算をする方法**

を身につけます。

NumPyが速い理由はここにあります。

---

# 講義（20分）

## Pythonらしい書き方

例えば全員に1点加点したいとします。

普通のPythonなら

```python
scores = [50, 60, 70]

new_scores = []

for s in scores:
    new_scores.append(s + 1)
```

AIでもできますが、遅いです。

---

NumPyなら

```python
import numpy as np

scores = np.array([50, 60, 70])

print(scores + 1)
```

結果

```
[51 61 71]
```

for文がありません。

NumPyは内部で高速なC言語実装を使っているため、このような書き方が速くなります。

---

## ベクトル化（Vectorization）

この

```
配列同士をまとめて計算する
```

考え方を

**ベクトル化**

と言います。

AIコードでは毎日のように使います。

---

## ブロードキャスト

NumPyには便利な仕組みがあります。

```python
A = np.array([
    [1,2],
    [3,4]
])

print(A + 10)
```

結果

```
11 12
13 14
```

10が自動的に全要素へ広がっています。

これが

**ブロードキャスト**

です。

---

## なぜ重要？

例えば画像。

```
高さ × 幅 × RGB
```

全部の画素に

```
255で割る
```

ことがよくあります。

```python
image = image / 255
```

これだけで終わります。

for文は不要です。

---

# 実習（40分）

## ① ベクトル同士

```python
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

print(a + b)
```

---

## ② 引き算

```python
print(a - b)
```

---

## ③ 掛け算

```python
print(a * b)
```

---

## ④ 割り算

```python
print(a / b)
```

---

## ⑤ スカラー演算

```python
print(a + 100)

print(a * 10)

print(a / 2)
```

---

## ⑥ ブロードキャスト

```python
A = np.array([
    [1,2],
    [3,4]
])

print(A + 10)
```

---

## ⑦ 行ごとに足す

```python
A = np.array([
    [1,2],
    [3,4]
])

v = np.array([10,20])

print(A + v)
```

結果

```
11 22
13 24
```

NumPyが自動で形を合わせています。

---

## ⑧ 列ごとに足す

```python
v = np.array([
    [10],
    [20]
])

print(A + v)
```

結果

```
11 12
23 24
```

同じ「足し算」でも、ベクトルの形によって結果が変わることに注目しましょう。

---

## ⑨ 平均を求める

```python
scores = np.array([70,80,90])

print(scores.mean())
```

---

## ⑩ 最大値・最小値

```python
print(scores.max())

print(scores.min())
```

データ分析や前処理では頻繁に使います。

---

# 演習（20分）

### 演習1

次の配列を作成してください。

```python
a = np.array([2,4,6,8])
```

以下を実行して結果を確認しましょう。

```python
a + 5
a * 3
a / 2
```

---

### 演習2

次の2つの配列を足してください。

```python
a = np.array([1,2,3])

b = np.array([10,20,30])
```

---

### 演習3

次の行列に

```python
[100, 200]
```

をブロードキャストして足してみましょう。

```python
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])
```

---

### 演習4

次の配列について

```python
scores = np.array([65,72,81,94,58])
```

以下を求めてください。

- 平均
- 最大値
- 最小値

---

# 今日のポイント

今日はAIコードを書く上で最も重要な考え方を学びました。

- **ベクトル化**：for文ではなく、配列全体を一度に計算する。
- **ブロードキャスト**：形の異なる配列同士でも、条件が合えば自動的に計算できる。

この2つを理解すると、NumPyやPyTorchのコードが「なぜこんなに短いのか」が見えてきます。

---

# 発展課題

`axis` 引数を使って、行方向・列方向ごとに平均を求めてみましょう。

```python
A.mean(axis=0)
A.mean(axis=1)
```

結果を見比べて、「どの方向に集計しているのか」を自分の言葉で説明できれば十分です。

---

## 次回予告

**第3回：NumPyインデックス・スライス・マスク操作**

AI開発では「必要なデータだけ取り出す」操作が非常に多くあります。次回は、NumPyでデータを自在に切り出すテクニックを学びます。

# AI工学101 — 第3回
## NumPyでデータを切る・選ぶ・絞る

今日は前回の**ベクトル演算・ブロードキャスト**の続き。テーマは **インデックス・スライス・Boolean Mask** です。

ここは地味に見えて、機械学習では猛烈に使います。

> 「1000件のデータから条件に合う237件だけ取り出す」

みたいな操作を、Pythonの `for` 文なしで書けるようになります。

**所要時間：60〜90分 / 講義20分 + 実習40分 + 演習20分**

---

## 📖 講義：AIにとって「データを選ぶ」とは

こんなデータがあるとします。

```python
import numpy as np

scores = np.array([42, 78, 91, 55, 83])
```

3番目の値が欲しいなら、

```python
scores[2]
```

結果は、

```text
91
```

Pythonと同じく**0始まり**ですね。

そしてNumPyでは、もっと強力なことができます。

```python
scores[scores >= 80]
```

結果：

```text
[91 83]
```

この一行では、

```text
scores >= 80
      ↓
[False, False, True, False, True]
      ↓
Trueの場所だけ取得
      ↓
[91, 83]
```

という処理が行われています。

これが **Boolean Mask（真偽値マスク）**。

後でscikit-learnを使うと、

```text
データ
 ↓
異常値を除く
 ↓
特定クラスを抽出
 ↓
訓練データとテストデータに分割
 ↓
モデルへ投入
```

といった処理を大量に行います。

つまり今日は**モデルに食わせるデータを料理する技術**です。🍳

---

# 💻 実習1：インデックス

まず一次元配列。

```python
a = np.array([10, 20, 30, 40, 50])

print(a[0])
print(a[2])
print(a[-1])
```

結果を予想してから実行してみてください。

特に、

```python
a[-1]
```

は「最後の要素」です。

---

# 💻 実習2：スライス

```python
print(a[1:4])
```

これは、

```text
index    0   1   2   3   4
value   10  20  30  40  50
             └───────┘
```

なので、

```text
[20 30 40]
```

になります。

基本形は、

```python
a[start:stop:step]
```

です。

例えば、

```python
a[::2]
```

なら1個飛ばし。

```text
[10 30 50]
```

---

# 💻 実習3：二次元配列を切る

ここからAIっぽくなります。

```python
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])
```

shapeを確認。

```python
print(X.shape)
```

```text
(4, 3)
```

4サンプル × 3特徴量、と考えることもできます。

---

## 行を取り出す

```python
print(X[1])
```

結果：

```text
[40 50 60]
```

---

## 一要素を取り出す

```python
print(X[1, 2])
```

結果：

```text
60
```

NumPyでは、

```python
X[行, 列]
```

と覚えると分かりやすいです。

---

## 列を丸ごと取り出す

```python
print(X[:, 1])
```

結果：

```text
[20 50 80 110]
```

この `:` が重要。

```text
X[:, 1]
│ │  └─ 1列目
│ └──── 全行
└────── X
```

つまり**全サンプルについて、特定の特徴量だけ取得**できます。

これは今後めちゃくちゃ使います。

---

# 💻 実習4：Boolean Mask

本日の主役です。

```python
scores = np.array([42, 78, 91, 55, 83])

mask = scores >= 80

print(mask)
```

結果：

```text
[False False  True False  True]
```

そして、

```python
print(scores[mask])
```

結果：

```text
[91 83]
```

一行でも書けます。

```python
scores[scores >= 80]
```

---

# 💻 実習5：複数条件

「60以上90未満」を取り出したい。

NumPyではこうします。

```python
scores[(scores >= 60) & (scores < 90)]
```

結果：

```text
[78 83]
```

ここで注意。

Pythonの、

```python
and
```

ではなく、

```python
&
```

を使います。

ORなら、

```python
|
```

です。

そして各条件を **`()` で囲む**。

これはNumPy初心者が一度は踏む地雷です💣

```python
(scores >= 60) & (scores < 90)
```

の形ごと覚えてしまってOK。

---

# 💻 実習6：実際のデータっぽくする

5人について、

```text
[勉強時間, テスト点数]
```

があるとします。

```python
data = np.array([
    [1.0, 45],
    [2.5, 62],
    [3.0, 70],
    [4.5, 88],
    [6.0, 95]
])
```

点数だけ取得。

```python
scores = data[:, 1]

print(scores)
```

```text
[45. 62. 70. 88. 95.]
```

80点以上の人を抽出します。

```python
high_score = data[data[:, 1] >= 80]

print(high_score)
```

結果：

```text
[[ 4.5 88. ]
 [ 6.  95. ]]
```

おお。

**「点数が80以上の行を丸ごと取得」**

できました。

これ、もう小さいながら**データサイエンスのコード**です。

---

# ✍️ 演習

ここからはレベル君のターン。

次のデータを使います。

```python
data = np.array([
    [25, 150],
    [30, 180],
    [35, 170],
    [40, 200],
    [45, 160],
    [50, 220]
])
```

各行を、

```text
[年齢, スコア]
```

とします。

### 問1〜5

1. すべての「年齢」だけを取得してください。
2. すべての「スコア」だけを取得してください。
3. スコアが180以上の人を、**行ごと**抽出してください。
4. 年齢が30以上45以下の人を抽出してください。
5. **年齢35以上 かつ スコア180以上**の人を抽出してください。

特に問5が今日のボス戦です👾

ヒントだけ置いておきます。

```python
data[
    (条件1) & (条件2)
]
```

答えはまだ書かないので、実際にNumPyで組んでみよう。

---

## 🌿 今日の到達点

第1回では「NumPy配列を作る」、第2回では「配列をまとめて計算する」、そして今回は、

> **配列から必要なデータだけ選択する**

ところまで来ました。

ここまでの3回で、

```python
X[:, 0]
X * 10
X[X[:, 1] >= 80]
A @ B
```

みたいな、**機械学習コードで普通に出てくるNumPy記法**がだいぶ読めるようになっています。

次の**第4回は `reshape`・次元・axis**。

ここで `(100,)` と `(100, 1)` が「似てるようで全然違う」という、AIエンジニアを定期的に殴ってくる **shape地獄🔥** に入ります。

# AI工学101 — 第4回
## shape地獄へようこそ 🔥 `reshape`・次元・`axis`

よし、今回はちゃんと**第3回の続き**だぞ😂  
前回までで「作る → 計算する → 選ぶ」まで来ました。

今日はAIコードで頻発する、

```text
ValueError: shapes ... not aligned
```

系エラーと仲良くなる回です。

**所要時間：60〜90分**  
講義20分 ＋ 実習40〜50分 ＋ 演習20分

---

## 📖 講義：shapeは「データの意味」でもある

まずこれ。

```python
import numpy as np

a = np.array([10, 20, 30])

print(a.shape)
```

結果：

```text
(3,)
```

3個の数字だから `(3,)`。

ではこれは？

```python
b = np.array([
    [10],
    [20],
    [30]
])

print(b.shape)
```

結果：

```text
(3, 1)
```

似てる。

でも、

```text
(3,)      ← 1次元ベクトル

(3, 1)    ← 3行1列の2次元行列
```

**別物です。**

さらに、

```python
c = np.array([[10, 20, 30]])
```

なら、

```text
(1, 3)
```

です。

図にすると、

```text
(3,)

[10 20 30]


(1, 3)

[[10 20 30]]


(3, 1)

[[10]
 [20]
 [30]]
```

同じ3個の数字なのに構造が違う。

ここが重要です。

---

## AIではshapeに意味がある

例えば機械学習では、典型的に入力データ `X` を、

```text
(samples, features)
```

というshapeで持ちます。

100人について、

```text
年齢
身長
体重
```

を記録したなら、

```text
(100, 3)
```

になります。

つまり、

```python
X.shape
```

を見れば、

> 100サンプル × 3特徴量

だと分かる。

後のPyTorchではさらに、

```text
(batch, channel, height, width)
```

などが出てきます。

だからAIエンジニアは、コードを読むときかなりの頻度で、

**「今このtensor、shape何？」**

と考えています。

shapeは住所みたいなもんです。

---

# 💻 実習1：`ndim`

次元数を調べてみます。

```python
a = np.array([1, 2, 3])

b = np.array([
    [1, 2, 3]
])

c = np.array([
    [1],
    [2],
    [3]
])

print(a.ndim)
print(b.ndim)
print(c.ndim)
```

予想してから実行してみてください。

結果は、

```text
1
2
2
```

です。

つまり、

```text
shape       ndim

(3,)          1
(1, 3)        2
(3, 1)        2
```

となります。

---

# 💻 実習2：`reshape`

6個の数字を作ります。

```python
a = np.arange(1, 7)

print(a)
print(a.shape)
```

結果：

```text
[1 2 3 4 5 6]

(6,)
```

これを2×3に変形。

```python
A = a.reshape(2, 3)

print(A)
```

```text
[[1 2 3]
 [4 5 6]]
```

shape：

```python
print(A.shape)
```

```text
(2, 3)
```

---

## 3×2にもできる

```python
B = a.reshape(3, 2)

print(B)
```

```text
[[1 2]
 [3 4]
 [5 6]]
```

重要なのは、

> **要素数そのものは変わらない**

ということ。

6個の数字なら、

```text
2 × 3 = 6
3 × 2 = 6
1 × 6 = 6
6 × 1 = 6
```

はOK。

しかし、

```python
a.reshape(4, 2)
```

は無理です。

8個必要なのに6個しかありません。

NumPy「湿った肉よ、算数をしろ」

となります。

---

# 💻 実習3：`-1` に計算させる

これはめちゃくちゃ便利。

```python
a.reshape(2, -1)
```

NumPyが、

```text
6要素
↓
2行
↓
じゃあ3列ですね
```

と推論します。

結果：

```text
(2, 3)
```

逆もできます。

```python
a.reshape(-1, 2)
```

結果：

```text
(3, 2)
```

AIコードで、

```python
X.reshape(-1, 1)
```

という記述を見かけたら、

> 「行数は自動計算して、1列の二次元データにしている」

と読めます。

---

# 💻 実習4：`axis` を理解する

ここは今日一番重要です。

```python
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
```

shapeは、

```text
(2, 3)
```

です。

まず全部の平均。

```python
A.mean()
```

結果：

```text
35
```

では、

```python
A.mean(axis=0)
```

を実行。

結果：

```text
[25. 35. 45.]
```

なぜ？

```text
10   20   30
↓    ↓    ↓
40   50   60

25   35   45
```

**axis=0方向を潰して集計**しています。

---

次。

```python
A.mean(axis=1)
```

結果：

```text
[20. 50.]
```

つまり、

```text
10 → 20 → 30  = 20

40 → 50 → 60  = 50
```

です。

ここで、

> axis=0 は縦  
> axis=1 は横

とだけ丸暗記すると、3次元以上で事故ります。

より正確には、

> **指定したaxisを消すように集計する**

と理解してください。

---

# 💻 実習5：shapeが消える様子を見る

```python
print(A.shape)
```

```text
(2, 3)
```

そして、

```python
x = A.mean(axis=0)

print(x.shape)
```

結果：

```text
(3,)
```

もともと、

```text
(2, 3)
 ↑
axis=0
```

だったものから0番目の軸が消え、

```text
(3,)
```

になった。

一方、

```python
y = A.mean(axis=1)

print(y.shape)
```

なら、

```text
(2,)
```

です。

この**「どの軸が消えた？」**という見方がかなり強いです。

---

# 💻 実習6：標準化を少しだけ先取り

機械学習で非常によく行う処理です。

```python
X = np.array([
    [160, 50],
    [170, 60],
    [180, 70]
])
```

仮に、

```text
身長 | 体重
```

だとします。

特徴量ごとの平均：

```python
mean = X.mean(axis=0)

print(mean)
```

結果：

```text
[170.  60.]
```

そして、

```python
X_centered = X - mean

print(X_centered)
```

すると、

```text
[[-10. -10.]
 [  0.   0.]
 [ 10.  10.]]
```

第2回の**ブロードキャスト**が帰ってきました。

つまり今、

```text
axisによる集計
      ↓
平均ベクトル
      ↓
ブロードキャスト
      ↓
データの中心化
```

と、以前の知識が接続されています。

これが後でscikit-learnの前処理につながります。

---

# ✍️ 演習：shape迷宮

次のデータを使います。

```python
X = np.arange(1, 13)
```

### 問1

現在の、

```python
X.shape
X.ndim
```

を確認してください。

### 問2

`reshape()` を使って、

```text
4行 × 3列
```

にしてください。

### 問3

その行列について、

```python
mean(axis=0)
```

を求めてください。

結果のshapeも確認します。

### 問4

今度は、

```python
mean(axis=1)
```

を求め、shapeを確認してください。

### 問5：ボス戦 👾

次があります。

```python
x = np.array([10, 20, 30, 40])
```

これを、

```text
[[10],
 [20],
 [30],
 [40]]
```

という形に変換してください。

ただし数字を手入力し直してはいけません。

`reshape()` を使います。

そして最終的な、

```python
x.shape
```

が、

```text
(4, 1)
```

になれば勝利です。

---

## 今日の到達点

ここまで4回で、

```text
第1回  ndarray・行列演算
        ↓
第2回  ベクトル化・broadcast
        ↓
第3回  slice・Boolean Mask
        ↓
第4回  reshape・shape・axis
```

まで来ました。

これ、単なるNumPy関数の暗記ではありません。

例えば、

```python
X[X[:, 1] >= 80]
```

を見て「条件抽出だ」と分かり、

```python
X.mean(axis=0)
```

を見て「サンプル方向を集約して特徴量ごとの平均を出してるな」と読める。

さらに、

```python
X.reshape(-1, 1)
```

を見て「1特徴量の二次元入力に整形してる」と読める。

**AIコードを読むための文法が少しずつ揃ってきています。**

次の**第5回は「線形代数をNumPyで実装する」**。

内積、行列積、転置、そして

\[
y = Wx + b
\]

に入ります。

ここでとうとう、今まで触ってきたNumPyが**ニューラルネットワークの計算そのもの**に接続します。リュール先生、いよいよAIの心臓部へ連れていきますぞ👨‍🏫🌿

# AI工学101 — 第5回
## NumPyで線形代数：`y = Wx + b` を自分の手で計算する

前回までで **配列 → ベクトル化 → データ抽出 → shape/axis** と進みました。

今日はとうとう、それらを一本につなげます。

\[
\boxed{y = Wx+b}
\]

ニューラルネットワークを開けると何度も出てくる、あいつです。👨‍🏫🌿

**所要時間：60〜90分**  
講義：約20分 ／ 実習：約40〜50分 ／ 演習：約20分

---

## 📖 講義：なぜAIで線形代数を使うのか

たとえば、ある人を

```text
年齢 = 30
身長 = 160
体重 = 55
```

と表現するとします。

NumPyなら、

```python
x = np.array([30, 160, 55])
```

ですね。

数学的には、

\[
x=
\begin{bmatrix}
30\\
160\\
55
\end{bmatrix}
\]

という**ベクトル**として扱えます。

つまり、

> 1人の人間 → 特徴量のベクトル

に変換したわけです。

画像だろうが文章だろうが音声だろうが、AIではこうやって数値表現に落とします。

---

## ① 内積

まず、

```python
x = np.array([1, 2, 3])
w = np.array([0.5, 1.0, -1.0])
```

として、

```python
print(np.dot(x, w))
```

を実行します。

内部では、

\[
1(0.5)+2(1.0)+3(-1.0)
\]

なので、

\[
0.5+2-3=-0.5
\]

となります。

つまり内積は、

> **各特徴量に重みを付けて全部足す**

操作だと見ることもできます。

これ、もう機械学習っぽいでしょう。

---

# 💻 実習1：内積を自力で確認する

```python
import numpy as np

x = np.array([2, 3, 4])
w = np.array([0.5, 2.0, -1.0])

y = np.dot(x, w)

print(y)
```

今度はNumPyを使わず、

```python
y_manual = (
    x[0] * w[0]
    + x[1] * w[1]
    + x[2] * w[2]
)

print(y_manual)
```

も実行してください。

同じ結果になるはずです。

ここで、

```python
np.dot(x, w)
```

が魔法ではなく、

```text
掛ける
 ↓
足す
```

をまとめてやっているだけだと確認できます。

---

# 📖 ② 行列積

今度は複数の重みを扱います。

```python
W = np.array([
    [1, 2],
    [3, 4]
])

x = np.array([
    [10],
    [20]
])
```

shapeを確認。

```python
print(W.shape)
print(x.shape)
```

結果：

```text
(2, 2)
(2, 1)
```

そして、

```python
y = W @ x

print(y)
```

計算は、

\[
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
\begin{bmatrix}
10\\
20
\end{bmatrix}
\]

なので、

\[
\begin{bmatrix}
1(10)+2(20)\\
3(10)+4(20)
\end{bmatrix}
=
\begin{bmatrix}
50\\
110
\end{bmatrix}
\]

になります。

---

## shapeだけで計算可能か判断できる

ここ重要。

```text
W     @    x

(2,2)      (2,1)
   ↑        ↑
   └── 2 = 2 ──┘
```

真ん中の数字が一致しているので計算できます。

結果のshapeは**外側**が残って、

```text
(2,1)
```

です。

一般化すると、

```text
(m, n) @ (n, p)

       ↓

     (m, p)
```

これを覚えるとshapeエラーへの耐性が猛烈に上がります。

---

# 💻 実習2：shapeを予想する

実行する**前に**答えてください。

```python
A = np.ones((3, 4))
B = np.ones((4, 2))

C = A @ B
```

`C.shape` は？

考え方は、

```text
(3, 4) @ (4, 2)
```

だから……

実際に確認。

```python
print(C.shape)
```

---

# 📖 ③ 転置 `T`

次はこちら。

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.shape)
```

```text
(2, 3)
```

転置すると、

```python
print(A.T)
```

```text
[[1 4]
 [2 5]
 [3 6]]
```

shapeは、

```text
(3, 2)
```

になります。

つまり、

\[
A_{2\times3}
\rightarrow
A^T_{3\times2}
\]

です。

機械学習では転置も頻出します。

---

# 💻 実習3：いよいよ `Wx+b`

入力：

```python
x = np.array([
    [2],
    [3]
])
```

重み：

```python
W = np.array([
    [0.5, 1.0],
    [-1.0, 2.0]
])
```

バイアス：

```python
b = np.array([
    [0.1],
    [0.2]
])
```

計算します。

```python
y = W @ x + b

print(y)
```

はい。

これです。

\[
\boxed{y=Wx+b}
\]

---

## 何が起きている？

まず、

```python
W @ x
```

で入力に重みを掛ける。

その後、

```python
+ b
```

でバイアスを加える。

つまり、

```text
入力 x
 │
 ▼
重み W
 │
 ▼
W @ x
 │
 ▼
バイアス +b
 │
 ▼
出力 y
```

となります。

この計算を大量に組み合わせたものがニューラルネットワークの基本構造です。

---

# 💻 実習4：複数サンプルを一気に処理

ここから今日の本丸。

3人のデータがあります。

```python
X = np.array([
    [1.0, 2.0],
    [2.0, 3.0],
    [4.0, 1.0]
])
```

shape：

```text
(3, 2)
```

つまり、

```text
3サンプル × 2特徴量
```

です。

重みを、

```python
W = np.array([
    [0.5],
    [2.0]
])
```

とします。

shape：

```text
(2,1)
```

すると、

```python
y = X @ W

print(y)
```

が計算できます。

shapeを追うと、

```text
(3,2) @ (2,1)

       ↓

     (3,1)
```

つまり、

> **3人分をfor文なしで一発計算**

しています。

第2回の「ベクトル化」がここにつながった。

---

# 💻 実習5：バイアスも追加

```python
b = 0.5

y = X @ W + b

print(y)
```

第2回でやったブロードキャストによって、すべてのサンプルに `0.5` が加算されます。

ここまでの知識が、

```text
ndarray
  ↓
shape
  ↓
ベクトル化
  ↓
broadcast
  ↓
行列積
  ↓
Wx+b
```

と一本につながりました。

---

# ✍️ 演習：小さな人工ニューロンを作る

次の入力を使います。

```python
X = np.array([
    [1.0, 3.0],
    [2.0, 1.0],
    [4.0, 2.0],
    [5.0, 3.0]
])
```

これは、

```text
4サンプル × 2特徴量
```

です。

重みは、

```python
W = np.array([
    [0.7],
    [-0.4]
])
```

バイアスは、

```python
b = 0.2
```

とします。

今回の課題は4つ。

1. `X.shape` と `W.shape` を確認する。
2. **コードを実行する前に** `X @ W` のshapeを予想する。
3. `y = X @ W + b` を計算する。
4. 1サンプル目について、NumPyを使わず手計算し、結果が一致するか確認する。

最後は、

\[
1.0(0.7)+3.0(-0.4)+0.2
\]

を計算すればOK。

---

## 🌿 第5回の核心

今日覚えてほしいのは関数名より、この構造です。

\[
\boxed{y=Wx+b}
\]

入力 `x` に対して、学習可能なパラメータ `W` と `b` を使い、別の数値表現 `y` へ変換する。

まだ**学習は一切していません**。

今は僕らが `W` を手入力しています。

ではAIの「学習」とは何なのか？

ものすごく乱暴に先取りすると、

> **正解に近づくように、この `W` と `b` を自動調整すること**

です。

ここ、重要。

ニューラルネットワークという巨大な概念が、急に、

```python
y = X @ W + b
```

という君がもう読めるNumPyコードまで降りてきました。

次の**第6回は「統計量とデータ前処理」**。平均・分散・標準偏差・標準化をNumPyで実装して、いよいよ「配列操作」から**機械学習用データを作る工程**へ進みます。👨‍🏫🥝